common: setting the locale globally
thorvg/thorvg pull request #1390
Opened 2023-04-22 00:24 UTC by mgrudzinska

Set the locale globally to avoid potential race
conditions between threads. It was set only when
reading the path attr, which could lead to crashes. The locale is now set from init() to term().

@Issue: https://github.com/thorvg/thorvg/issues/1389

2023-04-22 00:28 UTC, mgrudzinska commented
from [here](https://en.cppreference.com/w/cpp/locale/setlocale):
```Because setlocale modifies global state which affects execution of locale-dependent functions, it is undefined behavior to call it from one thread, while another thread is executing any of the following functions:...long list```

I don't know why setlocale was called only while path was read. doesn;t it make sense to use it globally? 
although I know, that user can change it between init and term, so this pr isn'l a perfect solution. maybe adding a comment in the init and term descriptions is a good idea?

2023-04-22 02:05 UTC, hermet commented
> from [here](https://en.cppreference.com/w/cpp/locale/setlocale): `Because setlocale modifies global state which affects execution of locale-dependent functions, it is undefined behavior to call it from one thread, while another thread is executing any of the following functions:...long list`
> 
> I don't know why setlocale was called only while path was read. doesn;t it make sense to use it globally? although I know, that user can change it between init and term, so this pr isn'l a perfect solution. maybe adding a comment in the init and term descriptions is a good idea?



> from [here](https://en.cppreference.com/w/cpp/locale/setlocale): `Because setlocale modifies global state which affects execution of locale-dependent functions, it is undefined behavior to call it from one thread, while another thread is executing any of the following functions:...long list`
> 
> I don't know why setlocale was called only while path was read. doesn;t it make sense to use it globally? although I know, that user can change it between init and term, so this pr isn'l a perfect solution. maybe adding a comment in the init and term descriptions is a good idea?

@mgrudzinska Obviously, app needs to change locale in a certain scenario so this is not a proper solution. Back to the origin, we need to revisit the svg parser it really needs setscale(). Currently, I can't remeber...

2023-04-22 02:06 UTC, hermet requested changes
This souldn't be applied.

2023-04-22 12:27 UTC, hermet commented
We need to check out the history of setlocale here...

2023-04-22 13:12 UTC, mgrudzinska commented
> We need to check out the history of setlocale here...

setlocale was used in efl, but we are parsing numbers differently - we don;t use locale sensitive functions like strtod, strotof, atoi etc (we have svgUtilStrtof)

but I just find out the isalpha, that we are using is locale sensitive. so I need to investigate.

2023-04-22 20:54 UTC, mgrudzinska commented
@hermet @JSUYA

in efl setlocale was used while parsing the path. In the SVG specs, the syntax for the path is described using EBNF, it is very well defined and there is no word about any locale specific characters that may appear there, so parsing should be independent on the locale settings.
In thorvg while path is parsed, isspace, isalpha and internally implemented svgUtilStrtof are used. I commented below in more details, but in general - the parsing is independent on locale setting.

svg tags like```text``` and ```id``` should be locale sensitive as they are right now in thorvg. 


In thirvg the following locale sensitive functions:
- ```isalpha()``` - used for parsing the path - only few ascii letters possible ([ref](https://www.w3.org/TR/SVG2/paths.html#TheDProperty)). whatever locale is set these symbols will be correctly recognized
- ```issapce()``` - SVG files are based on XML, which supports the Unicode character set. from [xml specs](https://www.w3.org/TR/2008/REC-xml-20081126/#NT-S) the possible white spaces: (#x20 | #x9 | #xD | #xA) (space/tab/carriage return/newline) and all of them will be universally recognized and not affected by locale settings.
- ```isdigit()``` and ```isxdigit()``` - from [here](https://en.cppreference.com/w/cpp/string/byte/isdigit): 
  ```isdigit and isxdigit are the only standard narrow character classification functions that are not affected by the currently installed C locale. although some implementations (e.g. Microsoft in 1252 codepage) may classify additional single-byte characters as digits.```
both used to parse path data, numbers, and coordinates that use the standard ASCII characters for decimal and hexadecimal digits, so the additional characters recognized as digit shouldn't affect anything.
- ```tolower()``` - used in ```svgUtilStrtof ``` to parse of special floating-point values (inf, infinity, and nan) - locale doesn;t matter
- ```atoi()``` - used to pars a thorvg version in tvg loader, tvgInitializer and svg2png - I can imagine that in the last one someone can call ```-r 4,000x4,000``` but it's so unlikely and counterintuitive...

2023-04-24 02:02 UTC, JSUYA commented
In https://github.com/thorvg/thorvg/issues/1389 I believe the reason for the crash is because locale is not thread safe(maybe?).
According to this article https://stackoverflow.com/questions/4057319/is-setlocale-thread-safe-function using `uselocale()` may be another workaround.

As you analyzed, we are using custom strtof instead of strtod, And I don't think removing is a problem if your analysis is correct.
However, I think we should take a more careful if we run into issues with this in the future, as it's very hard to track down.

2023-04-24 23:51 UTC, mgrudzinska commented
> https://stackoverflow.com/questions/4057319/is-setlocale-thread-safe-function

yes, if we need to set the locale, we have to provide solution for unix and for windows (uselocale is for unix only). 
sure it can be done, but the question is whether it is needed. 
also if we think that we need it, shouldn;t it be applied for the whole loading process? why path is so special?
I still think that it is not necessary to set the locale

2023-04-25 00:10 UTC, hermet approved these changes
@mgrudzinska If you think it's unnecessary, please push it.

2023-04-25 00:14 UTC, JSUYA approved these changes

2023-04-25 00:17 UTC, merged