utils: add sort method in tvgArray
thorvg/thorvg pull request #1584
Opened 2023-08-07 14:52 UTC by RuiwenTang

This PR does the following things:
* Add a new method in tvg::Array to support sort with custom comparer
* Add a associate unite test case to check the sort logical

The tessellation code in #1531 use tvg::Array as much as possible, and the algorithm need to sort Point , Edge.
So I add a the sort method in tvg::Array. This is a new method so there will be no impact on existing code.

2023-08-07 16:04 UTC, hermet requested changes
Please remove the test-case. We don't add it for the internal functions. Only extern APIs would have it.  Otherwise, Looks good to me. 

Thanks. :-)

2023-08-07 16:04 UTC, hermet commented on src/utils/tvgArray.h
> +                // while (i < j && arr[i] <= tmp) ++i;
does this comment necessary?

2023-08-08 00:15 UTC, RuiwenTang commented
@hermet Please take a look again :)

2023-08-08 01:40 UTC, hermet approved these changes
Great, looks good to me. thanks!

2023-08-08 01:41 UTC, hermet commented
Ah one more, could you please revise the commit message?

2023-08-08 02:01 UTC, RuiwenTang commented
> Ah one more, could you please revise the commit message? Remove -> Add a associate unite test case to check the sort logical

Sorry about the commit meesage, I have removed them

2023-08-09 02:08 UTC, merged