loader/svg: Revert part of 75e587a
thorvg/thorvg pull request #2207
Opened 2024-04-19 05:32 UTC by JSUYA

This patch reverts part of 75e587a for fix regression bug.
Even if unsupported elements are encountered, further parsing continues.

related issue: https://github.com/thorvg/thorvg/issues/2206

2024-04-21 09:36 UTC, hermet approved these changes

2024-04-21 09:43 UTC, hermet commented
You might wanna write a better commit msg title:
```
//clear to understand the purpose of this commit.
loader/svg: Fix a regression bug. 
loader/svg: Fix a part of patch due to a regression bug
```

2024-04-21 18:40 UTC, mgrudzinska requested changes
I think that the whole https://github.com/thorvg/thorvg/commit/75e587a9a9b8becbedc6f1ccacd88da95be1ccb4 should be reverted.

1. from the svg std:
[If an odd number of coordinates is provided, then the element is in error, with the same user agent behavior as occurs with an incorrectly specified path element.](https://www.w3.org/TR/SVG2/shapes.html#PolygonElement)
the path error handling is here: https://www.w3.org/TR/SVG2/paths.html#PathDataErrorHandling

In summary: for path data error handling, data should be read up until the first error occurs, and only the data up to that point should be rendered. 

As I understand, the same principle should apply to the points of a polygon. If there is an error in the data or an odd number of points is provided, then only the data loaded up to that point should be rendered.
@JSUYA do you agree or am I wrong?

2. ```if (!func(buf, bufLength, _attrParsePolygonNode, loader)) return nullptr;```
if we want to add this check, we should handle not only polygons, but all the node types we create. otherwise, the code will not be consistent

@JSUYA please check https://github.com/thorvg/thorvg/pull/2212 as the solution I'd apply

2024-04-22 01:46 UTC, JSUYA commented
> I think that the whole [75e587a](https://github.com/thorvg/thorvg/commit/75e587a9a9b8becbedc6f1ccacd88da95be1ccb4) should be reverted.
> 
> 1. from the svg std:
>    [If an odd number of coordinates is provided, then the element is in error, with the same user agent behavior as occurs with an incorrectly specified path element.](https://www.w3.org/TR/SVG2/shapes.html#PolygonElement)
>    the path error handling is here: https://www.w3.org/TR/SVG2/paths.html#PathDataErrorHandling
> 
> In summary: for path data error handling, data should be read up until the first error occurs, and only the data up to that point should be rendered.
> 
> As I understand, the same principle should apply to the points of a polygon. If there is an error in the data or an odd number of points is provided, then only the data loaded up to that point should be rendered. @JSUYA do you agree or am I wrong?
> 

Thank you for your detail information. you are right. I reviewed #2212. 

> 2. `if (!func(buf, bufLength, _attrParsePolygonNode, loader)) return nullptr;`
>    if we want to add this check, we should handle not only polygons, but all the node types we create. otherwise, the code will not be consistent

I think, if there is an object that should not be drawn when parsing is not processed properly, this syntax is resonable.
So far, we have only worked on valid images, so we created nodes regardless of the result of `func()`, but this may be needed more as we need to support it more widely through recent broken file testing. 
However, since it is currently difficult to check the parsing results of all specs, I think we can add more of these parts.
Of course, since this does not apply in this case, it is correct to revert my commit. :)
Thanks!

2024-04-22 01:46 UTC, closed without merging