web: Support viewport API
thorvg/thorvg pull request #2312
Opened 2024-05-24 00:58 UTC by tinyjin

Update web player to support viewport API. In rendering, the player will automatically detect visible element boundary and call viewport API.

https://github.com/thorvg/thorvg/assets/11167117/37a43935-1b2e-4876-8738-0939d0db53a5

Issue: #2292

2024-05-24 01:33 UTC, hermet commented
@tinyjin Could you please share the performance difference before and after? As the content size(resolution) is bigger, the difference should be more obvious.

2024-05-24 03:52 UTC, tinyjin commented
@hermet I see roughly 30% of enhancement in FPS. Please check details :)

**[Test Machine]**
- MacOS Sonoma 14.4.1
- Chip: Apple M1 Pro
- Memory: 16GB
- Chrome: Version 124.0.6367.208 (Official Build) (arm64)
- Screen Resolution: 1512 x 858 (pixels)
- Animation Resolution: 800 x 800 (pixels)
- Rendered Animations: 3 animations, half area visible

[Before]
80-90FPS

https://github.com/thorvg/thorvg/assets/11167117/b3f9acb7-f53d-4861-85c9-7141bdbe2d40

[After]
110-120FPS

https://github.com/thorvg/thorvg/assets/11167117/ec9913ae-1e99-42b5-8cab-528c439d08bb

2024-05-24 05:14 UTC, hermet commented
@theashraf

2024-05-24 06:56 UTC, hermet approved these changes

2024-05-27 07:02 UTC, hermet commented
@tinyjin could you please separate this to web/wasm?

2024-05-28 01:50 UTC, hermet requested changes
web repo has been changed.

2024-05-29 00:54 UTC, tinyjin commented
@hermet Ok, i'll update today!

2024-05-29 04:54 UTC, tinyjin commented
#2329

2024-05-29 04:54 UTC, closed without merging