lottie: add 'tp' tag support
thorvg/thorvg pull request #2326
Opened 2024-05-27 20:06 UTC by mgrudzinska

So far it hasn't been possible to specify
a matte layer - by default, it was the layer
above the calling layer. The 'tp' tag support
has been introduced, enabling referencing any
layer by its index.
In cases where the layer referencing the matte
was the first one, a segmentation fault was
observed. This issue has now been resolved.

@Issue: https://github.com/thorvg/thorvg/issues/2325

2024-05-28 01:20 UTC, hermet commented on src/loaders/lottie/tvgLottieParser.cpp
> +    Array<LottieLayer*> pendingLayers;
Now, this is becoming more than a parsing job. Please double-check the `_buildComposition()` function in `tvgLottieBuilder.cpp` I think that place is more appropriate to handle this.

2024-05-28 14:33 UTC, hermet requested changes
Please check a comment.

2024-05-29 02:23 UTC, hermet requested changes

2024-05-29 02:23 UTC, hermet commented on src/loaders/lottie/tvgLottieBuilder.cpp
> +            if (child->mid == -1 && prev) {
Hmm... it shouldn't take "tp" when prev is nullptr?  It should be something like this?
```
//by front
if (child->mid == -1) {
  if (c == children.begin()) err("sholudn't be happend?!");
  child->matte.target = *(c - 1);
//by index
} else {
   ...
}
```

2024-05-29 14:09 UTC, hermet commented
@mgrudzinska Could you please attach a test resource if you have?

2024-05-29 14:13 UTC, mgrudzinska commented
[matte-above.json](https://github.com/thorvg/thorvg/files/15485669/matte-above.json)
[matte-anim.json](https://github.com/thorvg/thorvg/files/15485671/matte-anim.json)
[matte-below.json](https://github.com/thorvg/thorvg/files/15485672/matte-below.json)
[matte-noMatte.json](https://github.com/thorvg/thorvg/files/15485673/matte-noMatte.json)
[matte-noTP.json](https://github.com/thorvg/thorvg/files/15485674/matte-noTP.json)

2024-05-29 14:18 UTC, closed without merging