API: revise the APIs.
thorvg/thorvg pull request #2334
Opened 2024-05-30 10:38 UTC by hermet

deprecate the `identifier()` APIs by renaming them to `type()`.

ThorVG is going to introduce an instance `id()`,
and this could be confused with the `identifier()` methods.

2024-05-30 12:07 UTC, mgrudzinska requested changes

2024-05-30 12:07 UTC, mgrudzinska commented on test/capi/capiShape.cpp
other capi tests are still using identifier

2024-05-30 13:51 UTC, mgrudzinska approved these changes

2024-05-31 02:12 UTC, tinyjin approved these changes

2024-05-31 02:16 UTC, hermet commented
please do not push.

2024-07-04 11:32 UTC, closed without merging