loaders: ensure a null terminator at the end of the data
thorvg/thorvg pull request #2392
Opened 2024-06-11 13:00 UTC by mgrudzinska

strlen does not count the null terminator - using it to determine the size of loaded data that is copied results in not copying the null terminator and may lead to memory corruption.

2024-06-11 13:07 UTC, mgrudzinska commented
rebased

2024-06-11 13:57 UTC, hermet commented
> strlen does not count the null terminator

hmm you changed about binary data, not strings. if someone uses the strlen() then that's the fix point?

2024-06-11 14:02 UTC, hermet requested changes
This doesn't make sense.

2024-06-12 03:21 UTC, hermet commented on src/loaders/lottie/tvgLottieLoader.cpp
>          memcpy((char*)content, data, size);
```
 memcpy(content, data, size);
```

2024-06-12 03:22 UTC, hermet approved these changes

2024-06-12 08:41 UTC, hermet commented
@mgrudzinska considering about this again, we can't prevent the scenario "non copy". Ultimately, this is an user error they should correct this.

2024-06-12 08:50 UTC, closed without merging