lottie: parse a number despite an incorrect type
thorvg/thorvg pull request #2393
Opened 2024-06-11 14:12 UTC by mgrudzinska

It may happen that a number which should be an int is actually a float. In such cases, a parsing error occurred and the animation was not rendered. Now,
an attempt is made to parse the number as a float
first, and only if this fails, the parsing is concluded with an error.

@Issue: https://github.com/thorvg/thorvg/issues/2389

2024-06-11 14:21 UTC, hermet commented
This might become a bit of an issue. Hiding issue by an engine side wouldn't be a good solution if there is a spec error, the usage must be corrected first.

2024-06-11 14:23 UTC, hermet requested changes
Please make it sure using getFloat() if the data expects the float.

2024-06-11 19:06 UTC, mgrudzinska commented
@hermet please check whether this is what you meant. I pushed changes

2024-06-12 03:04 UTC, hermet commented
You don't need to modify getInt() behavior. parser could call the getFloat() instead of getInt() if the data requires the float type.

2024-06-12 08:45 UTC, hermet commented
> @hermet am I allowed to introduce getNum() and inside decide which one to call: getInt or getFloat? or you mean that I should take care about this specific json and solve the problem only for the 'm' proparty of the repeater?

Basically, this is not a thorvg problem. I would like to confirm the root-cause first why this issue is occurred as I argued => "if the data requires the float type."

2024-07-01 08:27 UTC, hermet commented
Let's replace with this: https://github.com/thorvg/thorvg/pull/2507

2024-07-01 08:27 UTC, closed without merging