examples: fix crash in window creation
thorvg/thorvg pull request #2447
Opened 2024-06-23 04:56 UTC by tinyjin

SDL flag combination(SDL_WINDOW_HIDDEN | SDL_WINDOW_RESIZABLE) causes crash.

![CleanShot 2024-06-23 at 13 55 52@2x](https://github.com/thorvg/thorvg/assets/11167117/912266c4-35a9-4af3-ac2c-7ffaf1649e14)

2024-06-23 05:24 UTC, hermet requested changes
This doesn't make sense to me. The root-cause(thorvg) should be fixed, not example.
Could you please check with this https://github.com/thorvg/thorvg/pull/2441  ?

2024-06-24 02:36 UTC, hermet commented
@tinyjin hello, could you please confirm the `surface->pixel`, `surface->w`, `surface->h`, `surface->pitch` values?

![image](https://github.com/thorvg/thorvg/assets/3711518/bb0c757a-9deb-4179-af7b-22a055ace096)

2024-06-24 03:30 UTC, JSUYA reviewed
Regardless of whether it crashed or not,,,, the reason the window was displayed even if it was HIDDEN is because SDL_ShowWindow() is called.
If you want to change HIDDEN to SHOWN, SDL_ShowWindow() is unnecessary.

2024-06-25 00:45 UTC, mgrudzinska commented
@tinyjin please check https://github.com/thorvg/thorvg/pull/2466 whether this solves your case

2024-06-25 11:46 UTC, tinyjin commented
@mgrudzinska #2466 with macOS doesn't happen runtime crash in example. Thanks.

2024-06-25 11:46 UTC, closed without merging