wg_engine: introduce simultaneous flag support for strokes trimming
thorvg/thorvg pull request #2577
Opened 2024-07-19 20:41 UTC by SergeyLebedkin

[StrokeTrim](https://github.com/thorvg/thorvg/issues/2435) example

![image](https://github.com/user-attachments/assets/89dde3da-4826-4ca2-acd2-e264b3db140f)

2024-07-25 13:39 UTC, mgrudzinska requested changes
please handle correctly values < 0
[d.json](https://github.com/user-attachments/files/16378336/d.json)

2024-07-25 18:52 UTC, mgrudzinska approved these changes

2024-07-27 17:41 UTC, mgrudzinska commented
@SergeyLebedkin please double check, since introduces some changes https://github.com/thorvg/thorvg/pull/2596.
so you should interpret/wrap the begin/end values inside wg_engine (as I remember (-0.5,0.5) may be a problem

2024-07-29 04:36 UTC, SergeyLebedkin commented
> @SergeyLebedkin please double check, since introduces some changes #2596. so you should interpret/wrap the begin/end values inside wg_engine (as I remember (-0.5,0.5) may be a problem

I think that this will make a sense when we will stabilize all rules in #2596. So I will make a changes on this PR by folowing the last changes that will be approved

2024-07-31 18:22 UTC, SergeyLebedkin commented on src/renderer/wg_engine/tvgWgRenderData.cpp
> +    if (!rshape.stroke->strokeTrim(trimBegin, trimEnd)) { trimBegin = 0.0f; trimEnd = 1.0f; }
fixed

2024-07-31 18:31 UTC, mgrudzinska approved these changes

2024-08-01 03:05 UTC, hermet approved these changes

2024-08-01 03:07 UTC, merged