svg_loader: Adjust hsl values out of range
thorvg/thorvg pull request #2679
Opened 2024-08-26 04:13 UTC by JSUYA

The range of saturation and brightness values is 0 ~ 100%.
If a value greater than 100% is loaded, it will be modified to be 100%.

issue: https://github.com/thorvg/thorvg/issues/2678

2024-08-27 03:35 UTC, hermet approved these changes

2024-08-27 05:35 UTC, JSUYA commented
rebased :)

2024-08-27 14:53 UTC, mgrudzinska requested changes
since we are changing this I'd handle all the edge cases:

``` 
saturation = std::max(0.0f, std::min(saturation, 1.0f));
brightness = std::max(0.0f, std::min(brightness, 1.0f));
```

also hue value can be improved. we can use fmod instead of casting into uint, since this like an angle and can be < 0 (l.717)

source: https://www.w3.org/TR/css-color-3/#hsl-color

2024-08-27 14:56 UTC, mgrudzinska commented
sample to test:
[hsl.svg.zip](https://github.com/user-attachments/files/16764079/hsl.svg.zip)


expected result:
<img width="586" alt="Zrzut ekranu 2024-08-27 o 16 54 59" src="https://github.com/user-attachments/assets/16dc195a-62c8-458e-ba5f-3c86e458abdc">

2024-08-27 15:27 UTC, mgrudzinska reviewed
@JSUYA I should have left a comment instead of request changes, because this pr is correct, just can be improved, I think. sorry for that.

2024-08-28 01:21 UTC, JSUYA commented
> since we are changing this I'd handle all the edge cases:
> 
> ```
> saturation = std::max(0.0f, std::min(saturation, 1.0f));
> brightness = std::max(0.0f, std::min(brightness, 1.0f));
> ```
> 
> also hue value can be improved. we can use fmod instead of casting into uint, since this like an angle and can be < 0 (l.717)
> 
> source: https://www.w3.org/TR/css-color-3/#hsl-color

Thank you for detail. I modified PR. :)

2024-08-29 10:03 UTC, mgrudzinska approved these changes

2024-08-29 10:05 UTC, merged