wg_engine: clippath optimization
thorvg/thorvg pull request #2899
Opened 2024-10-22 21:05 UTC by SergeyLebedkin

Full review of clipping workflow.

Before we are used separate render target for each clip path and compute shader to find clip path intersections with AND logic.
Now we are using depth buffer and transactions from depth to stencil and back to get ind logic intersections,
Compute shaders, layouts and pipelines was removed

Result:
![image](https://github.com/user-attachments/assets/ca528dfb-641f-42a8-8984-ac07f2252553)

Few clippathes on the single frame (Before/After)
![image](https://github.com/user-attachments/assets/ba8bcbc6-dbc3-4bc2-a8ff-be5174c6d86c)

Massive clippathes on the single frame (Before/After)
![image](https://github.com/user-attachments/assets/59c598cc-142e-4d7a-8207-2d854c67535b)

2024-10-23 12:26 UTC, hermet commented
@SergeyLebedkin Thanks, please double check regressions, 3 svgs (red circles) are not displayed after this patch.

[before/after]
![image](https://github.com/user-attachments/assets/372b7235-8b71-45a9-846a-1ac525893e9a)

2024-10-23 12:27 UTC, hermet requested changes
please check a comment.

2024-10-23 12:27 UTC, SergeyLebedkin commented
@hermet seems to all its an image processing... I will check it. Thanx for reporting

2024-10-23 12:49 UTC, SergeyLebedkin commented
> please check a comment.

fixed

2024-10-23 13:15 UTC, tinyjin commented
@SergeyLebedkin 
From browser, it shows significant performance improvement in `5317-fireworkds.json` example.

![CleanShot 2024-10-23 at 22 12 22@2x](https://github.com/user-attachments/assets/4ae0edb8-e403-4b67-a196-488cb1cff674)

As a result in the fireworks animation, improved `48%+` (63FPS in AVG to 120FPS). This animation's lowest FPS was 26FPS, now consistenly animates in 120FPS.

2024-10-23 13:22 UTC, tinyjin approved these changes

2024-10-23 14:11 UTC, hermet commented
@SergeyLebedkin please check red circles:

![image](https://github.com/user-attachments/assets/5d1bc379-e4e9-4827-8162-db9414465b5d)

2024-10-23 16:05 UTC, SergeyLebedkin commented
@hermet 
> @SergeyLebedkin please check red circles:
Seeps to all wrong transformation for a clippath used in a case, if multiple clippases used for a shape.

Fixed

2024-10-24 02:18 UTC, hermet approved these changes

2024-10-24 02:19 UTC, hermet commented
@SergeyLebedkin Could you please refine the commit message? Thanks.

2024-10-24 08:25 UTC, SergeyLebedkin commented
> @SergeyLebedkin Could you please refine the commit message? Thanks.

Fixed

2024-10-24 08:49 UTC, merged