Replaced longjmp with returns.
thorvg/thorvg pull request #3012
Opened 2024-11-28 09:31 UTC by dragostis

Since longjmp is not yet fully supported on Wasm (emscripten uses JS to make the jumps and requires slow jumps), but also because longjmp is hard to reason about, this patch replaces it with return values. The logic stays exactly the same.

2024-11-28 21:38 UTC, mgrudzinska approved these changes

2024-11-29 07:47 UTC, dragostis commented
Thanks for the review! Since it's my first PR, could you please enable he workflows to run? Also, is there anything else I can do?

2024-11-29 10:40 UTC, hermet requested changes
Thanks but some broken occurred after this patch.

Examples/StrokeTrim:
![image](https://github.com/user-attachments/assets/a2aa738a-833a-4f80-9bfe-f7cd740c73aa)

Normal:
![image](https://github.com/user-attachments/assets/6b4ac1bc-d309-44d8-8cfd-eb50464860fe)

2024-12-02 17:26 UTC, hermet commented
> I've tried to reproduce this locally, but it renders fine. Does this reproduce at any resolution or is it resolution-dependent?

@dragostis Hi, I think the issue can be reproduced using the ThorVG example if the size is left unchanged. The problem might be related to system differences if you can't reproduce it. I confirmed that the issue is reproducible on both Linux and Windows but haven’t tested it on macOS.

2024-12-03 01:36 UTC, mgrudzinska commented
@dragostis The same happens on mac, but I found the problem.
Please make sure that all `_lineTo` calls are enclosed within an `if` statement: see lines 702 and 740 (the latter is responsible for the issue in the StrokeTrim example).

2024-12-03 01:54 UTC, mgrudzinska commented
@dragostis After addressing the above, could you please doublecheck whether the condition `if (rw.cellsCnt >= rw.maxCells)` evaluates to `true` the same number of times before and after the changes?

2024-12-03 08:59 UTC, dragostis commented
@mgrudzinska, thanks for the observation! I have no idea how I managed to miss a bunch of calls twice, but I double-checked now and I think it's fine.

2024-12-03 10:28 UTC, hermet approved these changes

2024-12-03 10:37 UTC, mgrudzinska commented
> @dragostis After addressing the above, could you please doublecheck whether the condition `if (rw.cellsCnt >= rw.maxCells)` evaluates to `true` the same number of times before and after the changes?

@dragostis did you double check this as well?

2024-12-03 10:40 UTC, hermet commented
@dragostis Thanks for your awesome contribution, before submitting this, 2 requests here:
1. Add yourself "Dragoș Tiselice <dragos@lottiefiles.com>" to `throvg/AUTHORS` file
![image](https://github.com/user-attachments/assets/6af3856d-63d9-4201-b344-6619be24479a)

2. Keep the consistency of the commit header message like:
```
    sw_engine: replaced longjmp with returns

    Since longjmp is not yet fully supported on Wasm (emscripten uses
    JS to make the jumps and requires slow jumps), but also because
    longjmp is hard to reason about, this patch replaces it with
    return values. The logic stays exactly the same.
```

2024-12-03 11:13 UTC, mgrudzinska commented
> > @dragostis After addressing the above, could you please doublecheck whether the condition `if (rw.cellsCnt >= rw.maxCells)` evaluates to `true` the same number of times before and after the changes?
> 
> @dragostis did you double check this as well?

sorry for bothering you with this, I checked, it's exactly the same number, perfect!

2024-12-03 11:22 UTC, dragostis commented
@hermet, I added myself as an author and fixed the commit title.

@mgrudzinska, no worries at all!

Thank you for helping me land this! :)

2024-12-03 11:27 UTC, merged